# H2 Console 활성화 (웹에서 DB 확인 가능)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 DB 연결 설정
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA 설정 (테이블 자동 생성)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mustache 설정
spring.mustache.servlet.expose-request-attributes=true
spring.mustache.servlet.expose-session-attributes=true
